import type { Product } from './types';

export const seedProducts: Product[] = [
  // ── Middle Eastern pantry ─────────────────────────────────────────
  {
    id: 'p-zaatar',
    name: "Sultan's Za'atar Blend",
    nameAr: 'زعتر فلسطيني',
    description:
      "Hand-blended Palestinian za'atar with wild thyme, sumac, sesame, and a touch of olive oil.",
    category: 'middle-eastern',
    subcategory: 'spices',
    price: 8.49,
    unit: '8 oz jar',
    stock: 42,
    badges: ['house made', 'imported herbs'],
    emoji: '🌿',
    gradient: 'from-emerald-600 to-emerald-900',
    origin: 'Nablus, Palestine',
  },
  {
    id: 'p-olive-oil',
    name: 'Nabali Extra Virgin Olive Oil',
    nameAr: 'زيت زيتون نابالي',
    description:
      'First cold press from single-estate Nabali olives. Grassy, peppery, unfiltered.',
    category: 'middle-eastern',
    subcategory: 'oils',
    price: 28.0,
    unit: '1 L tin',
    stock: 26,
    badges: ['single origin', 'unfiltered'],
    emoji: '🫒',
    gradient: 'from-emerald-500 to-emerald-800',
    origin: 'West Bank',
  },
  {
    id: 'p-tahini',
    name: 'Stone-Ground Tahini',
    nameAr: 'طحينة',
    description: 'Silky, nutty tahini ground in small batches. Pours like a dream.',
    category: 'middle-eastern',
    subcategory: 'pantry',
    price: 9.99,
    unit: '16 oz jar',
    stock: 58,
    badges: ['no additives'],
    emoji: '🥜',
    gradient: 'from-amber-400 to-amber-700',
    origin: 'Lebanon',
  },
  {
    id: 'p-pomegranate-molasses',
    name: 'Pomegranate Molasses',
    nameAr: 'دبس رمان',
    description: 'Thick, tart, glossy. The secret behind great muhammara.',
    category: 'middle-eastern',
    subcategory: 'pantry',
    price: 7.5,
    unit: '12 oz bottle',
    stock: 30,
    emoji: '🍷',
    gradient: 'from-rose-600 to-rose-900',
    origin: 'Syria',
  },
  {
    id: 'p-bulgur',
    name: 'Coarse Bulgur #3',
    nameAr: 'برغل',
    description: 'Parboiled cracked wheat — the backbone of tabbouleh and kibbeh.',
    category: 'middle-eastern',
    subcategory: 'grains',
    price: 4.25,
    unit: '2 lb bag',
    stock: 80,
    emoji: '🌾',
    gradient: 'from-yellow-500 to-yellow-800',
  },
  {
    id: 'p-freekeh',
    name: 'Smoked Freekeh',
    nameAr: 'فريكة',
    description: 'Green wheat, fire-roasted. Chewy and smoky — amazing with lamb.',
    category: 'middle-eastern',
    subcategory: 'grains',
    price: 6.99,
    unit: '2 lb bag',
    stock: 40,
    emoji: '🌾',
    gradient: 'from-lime-600 to-lime-900',
    origin: 'Jordan',
  },
  {
    id: 'p-sumac',
    name: 'Wild Sumac',
    nameAr: 'سماق',
    description: 'Tangy, ruby-red berries, coarsely ground. Sprinkle on everything.',
    category: 'middle-eastern',
    subcategory: 'spices',
    price: 5.49,
    unit: '4 oz jar',
    stock: 50,
    emoji: '🌺',
    gradient: 'from-red-600 to-red-900',
  },
  {
    id: 'p-rose-water',
    name: 'Damask Rose Water',
    nameAr: 'ماء ورد',
    description: 'Distilled from Damask roses. For sweets, tea, or a spritz on yogurt.',
    category: 'middle-eastern',
    subcategory: 'pantry',
    price: 6.25,
    unit: '10 oz bottle',
    stock: 35,
    emoji: '🌹',
    gradient: 'from-pink-400 to-rose-700',
  },
  {
    id: 'p-labneh',
    name: 'Fresh Labneh',
    nameAr: 'لبنة',
    description: 'Thick strained yogurt, tangy and creamy. House-made daily.',
    category: 'middle-eastern',
    subcategory: 'dairy',
    price: 5.99,
    unit: '16 oz tub',
    stock: 36,
    badges: ['house made', 'halal'],
    emoji: '🥛',
    gradient: 'from-stone-200 to-stone-500',
  },
  {
    id: 'p-feta',
    name: 'Bulgarian Sheep Feta',
    nameAr: 'جبنة فيتا',
    description: 'Crumbly, briny, sharp. Aged 60 days in barrels.',
    category: 'middle-eastern',
    subcategory: 'dairy',
    price: 11.5,
    unit: 'lb',
    stock: 22,
    emoji: '🧀',
    gradient: 'from-slate-200 to-slate-500',
    origin: 'Bulgaria',
  },
  {
    id: 'p-pita',
    name: 'Hand-Stretched Pita',
    nameAr: 'خبز عربي',
    description: 'Baked fresh every morning in our stone oven. Soft, pillowy pockets.',
    category: 'middle-eastern',
    subcategory: 'bakery',
    price: 3.99,
    unit: 'bag of 6',
    stock: 60,
    badges: ['baked today'],
    emoji: '🥖',
    gradient: 'from-amber-200 to-amber-500',
  },
  {
    id: 'p-maamoul',
    name: 'Date Maamoul',
    nameAr: 'معمول',
    description: 'Buttery semolina cookies stuffed with spiced dates.',
    category: 'sweets',
    subcategory: 'cookies',
    price: 14.0,
    unit: '1 lb box',
    stock: 18,
    emoji: '🍪',
    gradient: 'from-amber-500 to-orange-800',
  },
  {
    id: 'p-baklava',
    name: 'Pistachio Baklava',
    nameAr: 'بقلاوة',
    description: 'Layered phyllo with crushed Aleppo pistachios and rose syrup.',
    category: 'sweets',
    subcategory: 'pastry',
    price: 22.0,
    unit: '1 lb tray',
    stock: 14,
    badges: ['bestseller'],
    emoji: '🍯',
    gradient: 'from-yellow-400 to-orange-700',
  },
];
