import type { Product, Recipe, Driver, Order } from './types';
import { seedProducts as p1 } from './seed-products';
import { seedProducts2 as p2 } from './seed-products-2';
import { seedProducts3 as p3 } from './seed-products-3';

export const seedProducts: Product[] = [...p1, ...p2, ...p3];

export const seedRecipes: Recipe[] = [
  {
    id: 'r-tabbouleh',
    name: 'Classic Tabbouleh',
    nameAr: 'تبولة',
    cuisine: 'Levantine',
    description:
      'A bright, herbaceous parsley salad — more green than grain. The way it should be.',
    servings: 4,
    cookTimeMin: 25,
    difficulty: 'easy',
    emoji: '🥗',
    gradient: 'from-emerald-500 to-emerald-800',
    steps: [
      'Soak ¼ cup fine bulgur in cold water for 15 minutes, then drain well.',
      'Finely chop 3 bunches of parsley and ½ bunch of mint.',
      'Dice 2 Persian cucumbers and 2 vine-ripe tomatoes very small.',
      'Toss everything with juice of 2 lemons, ⅓ cup olive oil, salt, and a pinch of allspice.',
      'Rest 10 minutes so the bulgur finishes softening in the dressing, then serve on romaine leaves.',
    ],
    ingredients: [
      { productId: 'p-parsley', quantity: '3 bunches' },
      { productId: 'p-mint', quantity: '½ bunch' },
      { productId: 'p-cucumber', quantity: '2' },
      { productId: 'p-tomatoes', quantity: '2' },
      { productId: 'p-lemons', quantity: '2' },
      { productId: 'p-olive-oil', quantity: '⅓ cup' },
      { productId: 'p-bulgur', quantity: '¼ cup' },
    ],
  },
  {
    id: 'r-shishtaouk',
    name: 'Shish Taouk',
    nameAr: 'شيش طاووق',
    cuisine: 'Levantine',
    description: 'Yogurt-marinated grilled chicken skewers. Tangy, smoky, impossibly tender.',
    servings: 4,
    cookTimeMin: 45,
    difficulty: 'medium',
    emoji: '🍢',
    gradient: 'from-amber-500 to-orange-800',
    steps: [
      'Cube chicken thighs into 1.5" pieces.',
      'Whisk ½ cup labneh with juice of 1 lemon, 3 tbsp olive oil, 4 cloves grated garlic, 1 tsp sumac, salt, pepper, and a pinch of paprika.',
      'Marinate chicken 2+ hours (overnight if you can).',
      'Thread on skewers, grill on high heat 10–12 min total, turning once.',
      'Serve in warm pita with garlic sauce, pickles, and a dusting of sumac.',
    ],
    ingredients: [
      { productId: 'p-chicken-thighs', quantity: '2 lbs' },
      { productId: 'p-labneh', quantity: '½ cup' },
      { productId: 'p-lemons', quantity: '1' },
      { productId: 'p-olive-oil', quantity: '3 tbsp' },
      { productId: 'p-sumac', quantity: '1 tsp' },
      { productId: 'p-pita', quantity: '1 bag' },
    ],
  },
  {
    id: 'r-mujadara',
    name: 'Mujadara',
    nameAr: 'مجدرة',
    cuisine: 'Palestinian',
    description:
      'Lentils, rice, and deeply caramelized onions. Humble, but everyone asks for seconds.',
    servings: 6,
    cookTimeMin: 60,
    difficulty: 'easy',
    emoji: '🍚',
    gradient: 'from-stone-500 to-stone-800',
    steps: [
      'Slice 3 large onions thinly. Fry in plenty of olive oil over medium heat until deeply browned and crisp — 25 minutes, be patient.',
      'Rinse 1 cup brown lentils and simmer in 4 cups water for 20 minutes.',
      'Add 1 cup rinsed basmati or bulgur, 1 tsp cumin, 1 tsp salt, and half the onions. Cook another 20 minutes covered until rice is tender.',
      'Top with remaining onions. Serve with labneh and cucumber salad.',
    ],
    ingredients: [
      { productId: 'p-onions', quantity: '3 large' },
      { productId: 'p-olive-oil', quantity: '⅓ cup' },
      { productId: 'p-bulgur', quantity: '1 cup', optional: true },
      { productId: 'p-labneh', quantity: 'to serve' },
      { productId: 'p-cucumber', quantity: '2' },
    ],
  },
  {
    id: 'r-zaatar-manakish',
    name: "Za'atar Manakish",
    nameAr: 'مناقيش زعتر',
    cuisine: 'Palestinian',
    description: 'Flatbreads brushed with za\'atar-and-olive-oil paste. Breakfast of champions.',
    servings: 4,
    cookTimeMin: 30,
    difficulty: 'easy',
    emoji: '🫓',
    gradient: 'from-emerald-500 to-amber-700',
    steps: [
      'Mix ¼ cup za\'atar with ⅓ cup olive oil into a spreadable paste.',
      'Spread generously across pita rounds.',
      'Bake at 450°F for 5–7 minutes until edges crisp.',
      'Top with sliced tomato, cucumber, mint, a drizzle of more olive oil.',
    ],
    ingredients: [
      { productId: 'p-zaatar', quantity: '¼ cup' },
      { productId: 'p-olive-oil', quantity: '⅓ cup' },
      { productId: 'p-pita', quantity: '1 bag' },
      { productId: 'p-tomatoes', quantity: '1' },
      { productId: 'p-cucumber', quantity: '1' },
      { productId: 'p-mint', quantity: 'a few sprigs' },
    ],
  },
  {
    id: 'r-lamb-freekeh',
    name: 'Lamb Freekeh',
    nameAr: 'فريكة بالخروف',
    cuisine: 'Palestinian',
    description: 'Smoky green wheat simmered with slow-braised lamb. Weeknight impressive.',
    servings: 6,
    cookTimeMin: 120,
    difficulty: 'medium',
    emoji: '🍲',
    gradient: 'from-amber-700 to-stone-900',
    steps: [
      'Brown 2 lbs lamb shoulder in olive oil. Add 1 diced onion and 1 tsp allspice.',
      'Cover with water, simmer 1 hour until tender. Reserve 4 cups broth.',
      'Rinse 2 cups freekeh. Toast briefly in a pot.',
      'Add reserved broth + lamb. Cook 30–40 min until grain is chewy.',
      'Finish with a squeeze of lemon, toasted pine nuts, and a dollop of labneh.',
    ],
    ingredients: [
      { productId: 'p-lamb-shoulder', quantity: '2 lbs' },
      { productId: 'p-freekeh', quantity: '2 cups' },
      { productId: 'p-onions', quantity: '1 large' },
      { productId: 'p-lemons', quantity: '1' },
      { productId: 'p-labneh', quantity: '½ cup' },
    ],
  },
  {
    id: 'r-qahwa',
    name: 'Saudi Qahwa Service',
    nameAr: 'قهوة سعودية',
    cuisine: 'Arabian',
    description: 'A ritual, not a drink. Lightly-roasted, cardamom-forward, served with dates.',
    servings: 6,
    cookTimeMin: 15,
    difficulty: 'easy',
    emoji: '☕',
    gradient: 'from-amber-600 to-yellow-900',
    steps: [
      'Bring 4 cups water to a boil in a dallah.',
      'Add 3 tbsp Saudi Arabic coffee + 1 tbsp cracked cardamom pods. Simmer 10 min.',
      'Optionally add a pinch of saffron threads and 2 whole cloves.',
      'Pour into small finjan cups. Serve with Medjool dates on the side.',
    ],
    ingredients: [
      { productId: 'p-arabic-coffee', quantity: '3 tbsp' },
      { productId: 'p-cardamom-pods', quantity: '1 tbsp' },
      { productId: 'p-dates', quantity: '12' },
      { productId: 'p-finjan', quantity: '1', optional: true },
    ],
  },
];

export const seedDrivers: Driver[] = [
  { id: 'd-omar', name: 'Omar K.', phone: '+1-813-555-0142', vehicle: 'Ford Transit', color: '#2f7f5a' },
  { id: 'd-layla', name: 'Layla S.', phone: '+1-813-555-0177', vehicle: 'Honda CR-V', color: '#d49a1e' },
];

// Mock Tampa-area delivery addresses clustered around Sultan (28.0395, -82.4572).
const now = new Date();
const isoYesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString();
const isoToday = now.toISOString();

export const seedOrders: Order[] = [
  {
    id: 'o-1001',
    userId: 'u-demo',
    customerName: 'Amira Haddad',
    phone: '+1-813-555-0201',
    address: '4210 W Kennedy Blvd, Tampa, FL 33609',
    lat: 27.9446,
    lng: -82.5015,
    items: [
      { productId: 'p-zaatar', name: "Sultan's Za'atar Blend", price: 8.49, qty: 1, emoji: '🌿' },
      { productId: 'p-olive-oil', name: 'Nabali Extra Virgin Olive Oil', price: 28, qty: 1, emoji: '🫒' },
      { productId: 'p-pita', name: 'Hand-Stretched Pita', price: 3.99, qty: 2, emoji: '🥖' },
    ],
    subtotal: 44.47,
    deliveryFee: 4.99,
    tax: 3.34,
    total: 52.8,
    deliveryType: 'next-day',
    deliveryWindow: 'Tomorrow, 9am–12pm',
    status: 'confirmed',
    driverId: 'd-omar',
    createdAt: isoYesterday,
  },
  {
    id: 'o-1002',
    userId: 'u-demo',
    customerName: 'Yusuf Khoury',
    phone: '+1-813-555-0282',
    address: '2815 N Armenia Ave, Tampa, FL 33607',
    lat: 27.983,
    lng: -82.4823,
    items: [
      { productId: 'p-chicken-thighs', name: 'Boneless Chicken Thighs', price: 5.49, qty: 3, emoji: '🍗' },
      { productId: 'p-labneh', name: 'Fresh Labneh', price: 5.99, qty: 1, emoji: '🥛' },
      { productId: 'p-sumac', name: 'Wild Sumac', price: 5.49, qty: 1, emoji: '🌺' },
    ],
    subtotal: 27.95,
    deliveryFee: 4.99,
    tax: 2.1,
    total: 35.04,
    deliveryType: 'next-day',
    deliveryWindow: 'Tomorrow, 12pm–3pm',
    status: 'confirmed',
    driverId: 'd-omar',
    createdAt: isoYesterday,
  },
  {
    id: 'o-1003',
    userId: 'u-demo',
    customerName: 'Nadia Mansour',
    phone: '+1-813-555-0303',
    address: '10215 Palm River Rd, Tampa, FL 33619',
    lat: 27.9232,
    lng: -82.3685,
    items: [
      { productId: 'p-lamb-shoulder', name: 'Halal Lamb Shoulder', price: 14.99, qty: 3, emoji: '🍖' },
      { productId: 'p-freekeh', name: 'Smoked Freekeh', price: 6.99, qty: 1, emoji: '🌾' },
      { productId: 'p-baklava', name: 'Pistachio Baklava', price: 22, qty: 1, emoji: '🍯' },
    ],
    subtotal: 73.96,
    deliveryFee: 0,
    tax: 5.55,
    total: 79.51,
    deliveryType: 'next-day',
    deliveryWindow: 'Tomorrow, 3pm–6pm',
    status: 'packing',
    driverId: 'd-layla',
    createdAt: isoToday,
  },
  {
    id: 'o-1004',
    userId: 'u-demo',
    customerName: 'Hassan Darwish',
    phone: '+1-813-555-0410',
    address: '14502 Bruce B Downs Blvd, Tampa, FL 33613',
    lat: 28.0677,
    lng: -82.4312,
    items: [
      { productId: 'p-turkish-coffee', name: 'Turkish Coffee w/ Cardamom', price: 11.99, qty: 2, emoji: '☕' },
      { productId: 'p-dates', name: 'Medjool Dates', price: 12.99, qty: 1, emoji: '🌴' },
    ],
    subtotal: 36.97,
    deliveryFee: 4.99,
    tax: 2.77,
    total: 44.73,
    deliveryType: 'same-day',
    deliveryWindow: 'Today, 4pm–6pm',
    status: 'out-for-delivery',
    driverId: 'd-layla',
    createdAt: isoToday,
  },
  {
    id: 'o-1005',
    userId: 'u-demo',
    customerName: 'Samir Ayoub',
    phone: '+1-813-555-0555',
    address: '8209 N Florida Ave, Tampa, FL 33604',
    lat: 28.0154,
    lng: -82.4591,
    items: [
      { productId: 'p-shisha-doubleapple', name: 'Two Apples Shisha', price: 15.99, qty: 2, emoji: '🍎' },
      { productId: 'p-coco-coals', name: 'Coconut Hookah Coals', price: 12.99, qty: 1, emoji: '🔥' },
    ],
    subtotal: 44.97,
    deliveryFee: 4.99,
    tax: 3.37,
    total: 53.33,
    deliveryType: 'next-day',
    deliveryWindow: 'Tomorrow, 6pm–9pm',
    status: 'pending',
    driverId: null,
    createdAt: isoToday,
  },
];
