import type { Product } from './types';

export const seedProducts3: Product[] = [
  // ── Coffee & tea ──────────────────────────────────────────────────
  {
    id: 'p-turkish-coffee',
    name: 'Turkish Coffee with Cardamom',
    nameAr: 'قهوة عربية',
    description: 'Finely-milled dark roast blended with green cardamom.',
    category: 'coffee-tea',
    subcategory: 'coffee',
    price: 11.99,
    unit: '1 lb bag',
    stock: 32,
    badges: ['bestseller', 'cardamom'],
    emoji: '☕',
    gradient: 'from-amber-900 to-stone-900',
  },
  {
    id: 'p-arabic-coffee',
    name: 'Saudi Arabic Coffee (Qahwa)',
    nameAr: 'قهوة سعودية',
    description: 'Lightly roasted green coffee beans with cardamom, saffron, cloves.',
    category: 'coffee-tea',
    subcategory: 'coffee',
    price: 14.5,
    unit: '1 lb bag',
    stock: 20,
    emoji: '☕',
    gradient: 'from-amber-600 to-yellow-900',
  },
  {
    id: 'p-mint-tea',
    name: 'Maghreb Mint Tea',
    nameAr: 'شاي بالنعناع',
    description: 'Chinese gunpowder green tea blended with dried Nana mint.',
    category: 'coffee-tea',
    subcategory: 'tea',
    price: 7.99,
    unit: '8 oz tin',
    stock: 40,
    emoji: '🍵',
    gradient: 'from-green-600 to-teal-900',
  },
  {
    id: 'p-cardamom-pods',
    name: 'Green Cardamom Pods',
    description: 'Whole, vivid-green pods. The good stuff.',
    category: 'coffee-tea',
    subcategory: 'spices',
    price: 9.99,
    unit: '4 oz jar',
    stock: 28,
    emoji: '🫘',
    gradient: 'from-green-500 to-green-800',
  },
  {
    id: 'p-finjan',
    name: 'Brass Dallah Coffee Pot',
    description: 'Traditional long-spouted Arabic coffee pot. Hand-hammered brass.',
    category: 'coffee-tea',
    subcategory: 'ware',
    price: 48.0,
    unit: '1 pot',
    stock: 8,
    badges: ['handmade'],
    emoji: '🫖',
    gradient: 'from-yellow-500 to-amber-900',
  },

  // ── Hookah ────────────────────────────────────────────────────────
  {
    id: 'p-shisha-doubleapple',
    name: 'Two Apples Shisha',
    nameAr: 'تفاحتين',
    description: 'The classic. Rich double-apple with a whisper of anise.',
    category: 'hookah',
    subcategory: 'tobacco',
    price: 15.99,
    unit: '250g tub',
    stock: 60,
    badges: ['21+'],
    emoji: '🍎',
    gradient: 'from-red-700 to-red-950',
  },
  {
    id: 'p-shisha-mint',
    name: 'Iced Mint Shisha',
    description: 'Crisp, cooling mint with a long finish.',
    category: 'hookah',
    subcategory: 'tobacco',
    price: 15.99,
    unit: '250g tub',
    stock: 45,
    badges: ['21+'],
    emoji: '🌿',
    gradient: 'from-teal-600 to-emerald-900',
  },
  {
    id: 'p-coco-coals',
    name: 'Coconut Hookah Coals',
    description: 'Clean-burning coconut shell cubes. 72 pieces.',
    category: 'hookah',
    subcategory: 'accessories',
    price: 12.99,
    unit: '1 kg box',
    stock: 80,
    emoji: '🔥',
    gradient: 'from-stone-700 to-stone-950',
  },
  {
    id: 'p-hookah-khalil',
    name: 'Khalil Mamoon Hookah',
    description: 'Egyptian handcrafted, brass stem, 30" traditional shape.',
    category: 'hookah',
    subcategory: 'pipes',
    price: 189.0,
    unit: '1 hookah',
    stock: 5,
    badges: ['handmade', 'imported'],
    emoji: '💨',
    gradient: 'from-yellow-600 to-stone-900',
  },
];
