import type { Product } from './types';

export const seedProducts2: Product[] = [
  // ── Produce ───────────────────────────────────────────────────────
  {
    id: 'p-tomatoes',
    name: 'Vine-Ripe Tomatoes',
    description: 'Florida-grown, picked ripe, juicy and fragrant.',
    category: 'produce',
    subcategory: 'vegetables',
    price: 2.49,
    unit: 'lb',
    stock: 120,
    emoji: '🍅',
    gradient: 'from-red-400 to-red-700',
  },
  {
    id: 'p-cucumber',
    name: 'Persian Cucumbers',
    description: 'Crunchy, thin-skinned, barely a seed. Snack or slice.',
    category: 'produce',
    subcategory: 'vegetables',
    price: 3.29,
    unit: 'lb',
    stock: 90,
    emoji: '🥒',
    gradient: 'from-green-400 to-green-700',
  },
  {
    id: 'p-parsley',
    name: 'Flat-Leaf Parsley',
    description: 'Big, flavorful bunches. The soul of tabbouleh.',
    category: 'produce',
    subcategory: 'herbs',
    price: 1.49,
    unit: 'bunch',
    stock: 70,
    emoji: '🌿',
    gradient: 'from-emerald-400 to-emerald-700',
  },
  {
    id: 'p-mint',
    name: 'Fresh Mint',
    description: 'Fragrant spearmint. Tea, tabbouleh, everything.',
    category: 'produce',
    subcategory: 'herbs',
    price: 1.79,
    unit: 'bunch',
    stock: 60,
    emoji: '🌱',
    gradient: 'from-teal-400 to-teal-700',
  },
  {
    id: 'p-onions',
    name: 'Sweet Yellow Onions',
    description: 'Mild, sweet, perfect for cooking down.',
    category: 'produce',
    subcategory: 'vegetables',
    price: 1.29,
    unit: 'lb',
    stock: 150,
    emoji: '🧅',
    gradient: 'from-yellow-300 to-amber-600',
  },
  {
    id: 'p-lemons',
    name: 'Meyer Lemons',
    description: 'Sweeter, floral, thinner-skinned. Can be eaten skin and all.',
    category: 'produce',
    subcategory: 'citrus',
    price: 3.99,
    unit: 'lb',
    stock: 50,
    emoji: '🍋',
    gradient: 'from-yellow-300 to-yellow-600',
  },
  {
    id: 'p-eggplant',
    name: 'Baby Italian Eggplant',
    description: 'Tender, few seeds, perfect for makdous or baba ghanoush.',
    category: 'produce',
    subcategory: 'vegetables',
    price: 2.99,
    unit: 'lb',
    stock: 45,
    emoji: '🍆',
    gradient: 'from-purple-500 to-purple-900',
  },
  {
    id: 'p-dates',
    name: 'Medjool Dates',
    nameAr: 'تمر مجهول',
    description: 'Giant, soft, caramel-sweet. Jordan Valley harvest.',
    category: 'produce',
    subcategory: 'dried',
    price: 12.99,
    unit: '1 lb',
    stock: 40,
    badges: ['premium'],
    emoji: '🌴',
    gradient: 'from-amber-700 to-stone-800',
    origin: 'Jordan Valley',
  },

  // ── Meats & chicken (halal) ───────────────────────────────────────
  {
    id: 'p-lamb-shoulder',
    name: 'Halal Lamb Shoulder',
    nameAr: 'كتف خروف',
    description: 'Young, pasture-raised. Bone-in. Perfect for slow roasting.',
    category: 'meat',
    subcategory: 'lamb',
    price: 14.99,
    unit: 'lb',
    stock: 20,
    badges: ['halal', 'pasture-raised'],
    emoji: '🍖',
    gradient: 'from-rose-700 to-stone-900',
  },
  {
    id: 'p-lamb-ground',
    name: 'Ground Lamb',
    description: 'Freshly ground daily from shoulder trim.',
    category: 'meat',
    subcategory: 'lamb',
    price: 11.99,
    unit: 'lb',
    stock: 28,
    badges: ['halal'],
    emoji: '🥩',
    gradient: 'from-rose-600 to-stone-800',
  },
  {
    id: 'p-chicken-whole',
    name: 'Whole Halal Chicken',
    nameAr: 'دجاج كامل',
    description: 'Air-chilled, no antibiotics. About 4 lbs.',
    category: 'meat',
    subcategory: 'poultry',
    price: 3.99,
    unit: 'lb',
    stock: 35,
    badges: ['halal', 'no antibiotics'],
    emoji: '🍗',
    gradient: 'from-amber-400 to-amber-700',
  },
  {
    id: 'p-chicken-thighs',
    name: 'Boneless Chicken Thighs',
    description: 'Skinless, trimmed. Great for shish taouk.',
    category: 'meat',
    subcategory: 'poultry',
    price: 5.49,
    unit: 'lb',
    stock: 40,
    badges: ['halal'],
    emoji: '🍗',
    gradient: 'from-amber-500 to-orange-700',
  },
  {
    id: 'p-beef-kofta',
    name: 'Kofta Mix (Beef & Lamb)',
    description: 'Hand-mixed with parsley, onion, and seven-spice. Ready to grill.',
    category: 'meat',
    subcategory: 'prepared',
    price: 9.99,
    unit: 'lb',
    stock: 22,
    badges: ['halal', 'house made'],
    emoji: '🍢',
    gradient: 'from-red-700 to-stone-900',
  },
];
